load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_binary(
    name = "MainApp",
    main_class = "com.example.MainApp",
    srcs = ["src/main/scala/com/example/MainApp.scala"]
)